# Generated by Django 6.0.4 on 2026-05-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simmovement',
            name='movement_type',
            field=models.CharField(choices=[('receive', 'Received from Safaricom'), ('issue', 'Issued'), ('return', 'Returned'), ('transfer', 'Transferred'), ('flag', 'Fraud Flagged'), ('replace', 'Replaced'), ('register', 'Registered')], max_length=20),
        ),
    ]
