# Generated by Django 6.0.4 on 2026-05-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_simmovement_movement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sim',
            name='status',
            field=models.CharField(choices=[('in_stock', 'In Stock'), ('issued', 'Issued'), ('registered', 'Registered'), ('activated', 'Activated'), ('returned', 'Returned'), ('fraud_flagged', 'Fraud Flagged'), ('replaced', 'Replaced')], default='in_stock', max_length=20),
        ),
    ]
