# Generated by Django 6.0.4 on 2026-05-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_sim_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sim',
            name='status',
            field=models.CharField(choices=[('in_stock', 'In Stock'), ('issued', 'Issued'), ('registered', 'Registered'), ('activated', 'Activated'), ('returned', 'Returned'), ('fraud_flagged', 'Fraud Flagged'), ('lost', 'Lost'), ('faulty', 'Faulty'), ('replaced', 'Replaced')], default='in_stock', max_length=20),
        ),
        migrations.AlterField(
            model_name='simmovement',
            name='movement_type',
            field=models.CharField(choices=[('receive', 'Received from Safaricom'), ('issue', 'Issued'), ('return', 'Returned'), ('transfer', 'Transferred'), ('flag', 'Fraud Flagged'), ('replace', 'Replaced'), ('register', 'Registered'), ('lost', 'Lost / Missing'), ('faulty', 'Faulty SIM Reported')], max_length=20),
        ),
    ]
