# Generated by Django 6.0.4 on 2026-04-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0002_dealer_subscription_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='subscription_plan',
            field=models.CharField(choices=[('trial', 'Trial'), ('basic', 'Basic'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='trial', max_length=20),
        ),
    ]
