# Generated by Django 6.0.4 on 2026-04-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0003_alter_dealer_subscription_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10),
        ),
        migrations.AddField(
            model_name='dealer',
            name='next_billing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dealer',
            name='pending_plan_change',
            field=models.CharField(blank=True, choices=[('trial', 'Trial'), ('basic', 'Basic'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dealer',
            name='pending_plan_change_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='subscription_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='subscription_status',
            field=models.CharField(choices=[('active', 'Active'), ('trial', 'Trial'), ('overdue', 'Overdue'), ('suspended', 'Suspended')], default='trial', max_length=20),
        ),
    ]
