# Generated by Django 6.0.4 on 2026-04-29 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0004_dealer_billing_cycle_dealer_next_billing_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MobiGo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imis', models.CharField(blank=True, max_length=20)),
                ('mobigo_sim_number', models.CharField(blank=True, max_length=20)),
                ('sim_serial_number', models.CharField(blank=True, max_length=30)),
                ('ba_msisdn', models.CharField(blank=True, max_length=20)),
                ('agent_msisdn', models.CharField(blank=True, max_length=20)),
                ('device_type', models.CharField(choices=[('mobigo', 'MobiGo Device'), ('enrolled_phone', 'Enrolled Phone')], default='mobigo', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_ba', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobigo_device', to=settings.AUTH_USER_MODEL)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobigos', to='dealers.dealer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
