# Generated by Django 6.0.4 on 2026-05-02 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0005_mobigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='is_warehouse',
            field=models.BooleanField(default=False),
        ),
    ]
