# Generated by Django 6.0.4 on 2026-05-17 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0006_branch_is_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='is_demo',
            field=models.BooleanField(default=False, help_text='Demo dealer — resets nightly.'),
        ),
    ]
