# Generated by Django 6.0.4 on 2026-05-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionrecord',
            name='claimed_sims',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commissionrecord',
            name='disputed_sims',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commissionrecord',
            name='fraud_sims',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commissionrecord',
            name='not_in_inventory_sims',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commissionrecord',
            name='not_in_report_sims',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commissionrecord',
            name='rejected_sims',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
