# Generated by Django 6.0.4 on 2026-05-05 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0002_commissionrecord_claimed_sims_and_more'),
        ('dealers', '0006_branch_is_warehouse'),
        ('inventory', '0002_alter_simmovement_movement_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeductionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('violation_type', models.CharField(choices=[('stale_sim', 'SIM Held Too Long'), ('damaged', 'Damaged / Defective'), ('fraud', 'Fraud Flagged SIM'), ('lost', 'Lost / Unaccounted SIM'), ('manual', 'Manual Deduction')], max_length=20)),
                ('amount_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_per_day', models.BooleanField(default=False)),
                ('threshold_days', models.PositiveIntegerField(blank=True, null=True)),
                ('settlement_mode', models.CharField(choices=[('commission_deduction', 'Deduct from Commission'), ('standalone', 'Standalone Repayment')], default='commission_deduction', max_length=25)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealers.dealer')),
            ],
        ),
        migrations.CreateModel(
            name='DeductionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(max_length=20)),
                ('sims_count', models.PositiveIntegerField(default=1)),
                ('days_held', models.PositiveIntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('dismissed', 'Dismissed'), ('settled', 'Settled')], default='pending_approval', max_length=20)),
                ('settlement_mode', models.CharField(default='commission_deduction', max_length=25)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deduction_records', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deductions_approved', to=settings.AUTH_USER_MODEL)),
                ('raised_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deductions_raised', to=settings.AUTH_USER_MODEL)),
                ('settlement_cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commissions.commissioncycle')),
                ('sim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.sim')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commissions.deductionrule')),
            ],
        ),
    ]
