from django.urls import path
from .views import (
    CommissionRuleListCreateView,
    CommissionRuleDetailView,
    CommissionCycleListCreateView,
    CommissionCycleDetailView,
    CommissionRecordListCreateView,
    CommissionRecordDetailView,
    ApproveCommissionView,
    RejectCommissionView,
    PayoutRecordListCreateView,
    PayoutRecordDetailView,
    CloseCycleView,
    GenerateCycleRecordsView,
    DeductionRuleListCreateView,
    DeductionRuleDetailView,
    DeductionRecordListCreateView,
    DeductionRecordDetailView,
    ApproveDeductionView,
    DismissDeductionView,
    DeductionPendingCountView,
)

urlpatterns = [
    path("rules/",
         CommissionRuleListCreateView.as_view(),   name="rule_list"),
    path("rules/<int:pk>/",
         CommissionRuleDetailView.as_view(),       name="rule_detail"),
    path("cycles/",
         CommissionCycleListCreateView.as_view(),  name="cycle_list"),
    path("cycles/<int:pk>/",
         CommissionCycleDetailView.as_view(),      name="cycle_detail"),
    path("cycles/<int:pk>/close/",
         CloseCycleView.as_view(),                 name="cycle_close"),
    path("records/",
         CommissionRecordListCreateView.as_view(), name="record_list"),
    path("records/<int:pk>/",
         CommissionRecordDetailView.as_view(),     name="record_detail"),
    path("records/<int:pk>/approve/",
         ApproveCommissionView.as_view(),          name="record_approve"),
    path("records/<int:pk>/reject/",
         RejectCommissionView.as_view(),           name="record_reject"),
    path("payouts/",
         PayoutRecordListCreateView.as_view(),     name="payout_list"),
    path("payouts/<int:pk>/",
         PayoutRecordDetailView.as_view(),         name="payout_detail"),
    path("cycles/<int:pk>/generate/",
         GenerateCycleRecordsView.as_view(),       name="cycle_generate"),
    path("deduction-rules/",
         DeductionRuleListCreateView.as_view(),   name="deduction_rule_list"),
    path("deduction-rules/<int:pk>/",
         DeductionRuleDetailView.as_view(),       name="deduction_rule_detail"),
    path("deduction-records/",
         DeductionRecordListCreateView.as_view(), name="deduction_record_list"),
    path("deduction-records/<int:pk>/",
         DeductionRecordDetailView.as_view(),     name="deduction_record_detail"),
    path("deduction-records/<int:pk>/approve/",
         ApproveDeductionView.as_view(),          name="deduction_approve"),
    path("deduction-records/<int:pk>/dismiss/",
         DismissDeductionView.as_view(),          name="deduction_dismiss"),
    path("deduction-records/pending-count/",
         DeductionPendingCountView.as_view(),     name="deduction_pending_count"),
]
