// src/types/invoice.types.ts

// ── Invoice types that can be created manually by admin ───────────────────────
export type ManualInvoiceType =
  | "onboarding"
  | "commission"
  | "adjustment"
  | "manual";

// ── System-only invoice types (auto-generated by billing engine) ──────────────
export type SystemInvoiceType =
  | "subscription"
  | "overage"
  | "proration";

// ── All invoice types (used for display/filtering) ────────────────────────────
export type InvoiceType = SystemInvoiceType | ManualInvoiceType;

export type InvoiceSource = "system" | "admin";

export type InvoiceStatus = "draft" | "pending" | "paid" | "overdue" | "cancelled";

export type InvoicePeriod = "monthly" | "yearly" | "once";

export interface Invoice {
  id:           number;
  dealer:       number;
  dealer_details?: {
    id:   number;
    name: string;
  };

  invoice_type: InvoiceType;
  type_label:   string;   // computed by backend: "Subscription (Auto)", "Manual", etc.

  source:       InvoiceSource;
  source_label: string;   // "Auto" | "Manual"

  period:       InvoicePeriod;
  amount:       string;   // decimal string from DRF
  status:       InvoiceStatus;

  // Proration
  is_prorated:     boolean;
  original_amount: string | null;

  // Billing period this invoice covers
  billing_period_start: string | null;
  billing_period_end:   string | null;

  // Dates
  issued_date: string;
  due_date:    string;
  paid_at:     string | null;

  paid_by?:          number | null;
  paid_by_details?:  { id: number; full_name: string } | null;
  created_by?:       number | null;
  created_by_details?: { id: number; full_name: string } | null;

  notes:      string;
  created_at: string;
  updated_at: string;
}

export interface CreateInvoiceRequest {
  dealer:       number;
  invoice_type: ManualInvoiceType;  // only manual types allowed from UI
  period:       InvoicePeriod;
  amount:       number;
  status?:      InvoiceStatus;
  issued_date:  string;
  due_date:     string;
  notes?:       string;
}

export interface InvoiceFilters {
  dealer?:       number;
  status?:       InvoiceStatus;
  invoice_type?: InvoiceType;
  source?:       InvoiceSource;
}

// ── Labels ─────────────────────────────────────────────────────────────────────
export const INVOICE_TYPE_LABELS: Record<InvoiceType, string> = {
  subscription: "Subscription (Auto)",
  overage:      "Overage (Auto)",
  proration:    "Proration (Auto)",
  onboarding:   "Onboarding",
  commission:   "Commission",
  adjustment:   "Adjustment",
  manual:       "Manual",
};

// Types an admin can select when creating an invoice manually
export const MANUAL_INVOICE_TYPE_OPTIONS: {
  value: ManualInvoiceType;
  label: string;
}[] = [
  { value: "onboarding", label: "Onboarding Fee" },
  { value: "commission", label: "Commission"     },
  { value: "adjustment", label: "Adjustment"     },
  { value: "manual",     label: "Manual / Other" },
];