from django.db import models
from apps.accounts.models import User
from apps.dealers.models import Dealer


class Invoice(models.Model):

    class Status(models.TextChoices):
        DRAFT = "draft",     "Draft"
        PENDING = "pending",   "Pending"
        PAID = "paid",      "Paid"
        OVERDUE = "overdue",   "Overdue"
        CANCELLED = "cancelled", "Cancelled"

    class Period(models.TextChoices):
        MONTHLY = "monthly", "Monthly"
        YEARLY = "yearly",  "Yearly"
        ONCE = "once",    "One-time"

    class InvoiceType(models.TextChoices):
        SUBSCRIPTION = "subscription", "Subscription"   # system-generated only
        OVERAGE = "overage",      "Overage"        # system-generated only
        PRORATION = "proration",    "Proration"      # system-generated only
        ONBOARDING = "onboarding",   "Onboarding Fee"  # admin-created
        COMMISSION = "commission",   "Commission"     # admin-created
        ADJUSTMENT = "adjustment",   "Adjustment"     # admin-created
        MANUAL = "manual",       "Manual"         # admin-created

    class Source(models.TextChoices):
        SYSTEM = "system", "System"   # auto-generated by billing engine
        ADMIN = "admin",  "Admin"    # manually created from UI

    # ── Core ─────────────────────────────────────────────────────────────────
    dealer = models.ForeignKey(
        Dealer, on_delete=models.PROTECT, related_name="invoices")
    invoice_type = models.CharField(max_length=20, choices=InvoiceType.choices,
                                    default=InvoiceType.SUBSCRIPTION)
    source = models.CharField(max_length=10, choices=Source.choices,
                              default=Source.ADMIN)
    period = models.CharField(max_length=10, choices=Period.choices,
                              default=Period.MONTHLY)

    # ── Financials ────────────────────────────────────────────────────────────
    amount = models.DecimalField(max_digits=12, decimal_places=2)
    status = models.CharField(max_length=20, choices=Status.choices,
                              default=Status.PENDING)

    # ── Proration helpers ─────────────────────────────────────────────────────
    is_prorated = models.BooleanField(default=False)
    original_amount = models.DecimalField(max_digits=12, decimal_places=2,
                                          null=True, blank=True)

    # ── Billing period this invoice covers ───────────────────────────────────
    billing_period_start = models.DateField(null=True, blank=True)
    billing_period_end = models.DateField(null=True, blank=True)

    # ── Dates ─────────────────────────────────────────────────────────────────
    issued_date = models.DateField()
    due_date = models.DateField()
    paid_at = models.DateTimeField(null=True, blank=True)

    # ── Relationships ─────────────────────────────────────────────────────────
    paid_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True,
                                related_name="invoices_paid")
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True,
                                   related_name="invoices_created")

    # ── Meta ──────────────────────────────────────────────────────────────────
    notes = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return f"INV-{self.pk:04d} | {self.dealer.name} | {self.invoice_type} | KES {self.amount} [{self.status}]"


class PlanSetting(models.Model):
    plan = models.CharField(max_length=20, unique=True,
                            choices=Dealer._meta.get_field("subscription_plan").choices)
    label = models.CharField(max_length=50, default="")

    monthly_price = models.DecimalField(max_digits=10, decimal_places=2)
    yearly_price = models.DecimalField(max_digits=10, decimal_places=2)

    max_users = models.PositiveIntegerField(default=10)
    max_vans = models.PositiveIntegerField(default=5)
    max_branches = models.PositiveIntegerField(default=3)

    features = models.JSONField(default=list, blank=True)
    trial_days = models.PositiveIntegerField(null=True, blank=True,
                                             help_text="Only relevant for the trial plan")

    # ── Overage billing ───────────────────────────────────────────────────────
    allow_overage = models.BooleanField(default=False)
    overage_price_per_user = models.DecimalField(
        max_digits=10, decimal_places=2, default=0)
    overage_price_per_van = models.DecimalField(
        max_digits=10, decimal_places=2, default=0)
    overage_price_per_branch = models.DecimalField(
        max_digits=10, decimal_places=2, default=0)

    class Meta:
        db_table = "invoices_plan_settings"

    def __str__(self):
        return f"{self.plan} — KES {self.monthly_price}/mo"
