# Generated by Django 6.0.4 on 2026-04-19 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('dealers', '0004_dealer_billing_cycle_dealer_next_billing_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dealer_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='dealers.dealer'),
        ),
    ]
