# Generated by Django 6.0.4 on 2026-04-29 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_dealer_org'),
        ('dealers', '0005_mobigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('dealer_owner', 'Dealer Owner'), ('operations_manager', 'Operations Manager'), ('branch_manager', 'Branch Manager'), ('van_team_leader', 'Van Team Leader'), ('brand_ambassador', 'Brand Ambassador'), ('external_agent', 'External Agent'), ('finance', 'Finance Admin')], max_length=30),
        ),
        migrations.CreateModel(
            name='ExternalAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=255)),
                ('location', models.TextField(blank=True)),
                ('id_number', models.CharField(blank=True, max_length=50)),
                ('business_type', models.CharField(choices=[('shop', 'Shop'), ('kiosk', 'Kiosk'), ('supermarket', 'Supermarket'), ('pharmacy', 'Pharmacy'), ('hardware', 'Hardware'), ('other', 'Other')], default='shop', max_length=20)),
                ('business_type_other', models.CharField(blank=True, max_length=100)),
                ('commission_eligible', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_agents', to='dealers.dealer')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='external_agent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
