# Generated by Django 6.0.4 on 2026-05-04 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationrecord',
            name='agent_msisdn',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='reconciliationrecord',
            name='ba_msisdn',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='reconciliationrecord',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reconciliationrecord',
            name='fraud_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reconciliationrecord',
            name='identified_ba',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reconciliationrecord',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='reconciliationrecord',
            name='result',
            field=models.CharField(blank=True, choices=[('payable', 'Payable'), ('rejected', 'Rejected'), ('fraud', 'Fraud'), ('dispute', 'Dispute'), ('unmatched', 'Unmatched'), ('review', 'Manual Review')], default='unmatched', max_length=20),
        ),
        migrations.AddField(
            model_name='reconciliationrecord',
            name='topup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='safaricomreport',
            name='column_mapping',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='safaricomreport',
            name='filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='safaricomreport',
            name='period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='safaricomreport',
            name='period_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reconciliationrecord',
            name='registered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_registered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reconciliationrecord',
            name='sim_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('fraud_flagged', 'Fraud Flagged')], default='active', max_length=20),
        ),
    ]
