# Generated by Django 6.0.4 on 2026-05-08 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0006_branch_is_warehouse'),
        ('reconciliation', '0003_alter_reconciliationrecord_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='safaricomreport',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safaricom_reports', to='dealers.dealer'),
        ),
    ]
