# Generated by Django 6.0.4 on 2026-04-16 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dealers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPerformanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sims_issued', models.PositiveIntegerField(default=0)),
                ('sims_returned', models.PositiveIntegerField(default=0)),
                ('sims_registered', models.PositiveIntegerField(default=0)),
                ('sims_fraud', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_snapshots', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_snapshots', to='dealers.branch')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_snapshots', to='dealers.dealer')),
            ],
            options={
                'unique_together': {('date', 'dealer', 'branch', 'agent')},
            },
        ),
    ]
