# Generated by Django 6.0.4 on 2026-04-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_plansetting_invoice_is_prorated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plansetting',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='plansetting',
            name='label',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='plansetting',
            name='max_branches',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='plansetting',
            name='max_users',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='plansetting',
            name='max_vans',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='plansetting',
            name='trial_days',
            field=models.PositiveIntegerField(blank=True, help_text='Only relevant for the trial plan', null=True),
        ),
        migrations.AlterField(
            model_name='plansetting',
            name='plan',
            field=models.CharField(choices=[('trial', 'Trial'), ('basic', 'Basic'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], max_length=20, unique=True),
        ),
    ]
