# Generated by Django 6.0.4 on 2026-04-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_plansetting_features_plansetting_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plansetting',
            name='allow_overage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plansetting',
            name='overage_price_per_branch',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='plansetting',
            name='overage_price_per_user',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='plansetting',
            name='overage_price_per_van',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
