# Generated by Django 6.0.4 on 2026-04-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_plansetting_allow_overage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='billing_period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='billing_period_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='source',
            field=models.CharField(choices=[('system', 'System'), ('admin', 'Admin')], default='admin', max_length=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('subscription', 'Subscription'), ('overage', 'Overage'), ('proration', 'Proration'), ('onboarding', 'Onboarding Fee'), ('commission', 'Commission'), ('adjustment', 'Adjustment'), ('manual', 'Manual')], default='subscription', max_length=20),
        ),
    ]
